# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jslink',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
