# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 05:40
from __future__ import unicode_literals

from django.db import migrations
import djangocms_icon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_link', '0003_remove_jslink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='jslink',
            name='icon',
            field=djangocms_icon.fields.Icon(blank=True, default='fa-', max_length=255, verbose_name='Icon'),
        ),
    ]
