# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 15:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('js_link', '0005_jslink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jslink',
            name='svg',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.File', verbose_name='SVG Image'),
        ),
        migrations.AddField(
            model_name='jslinklist',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes'),
        ),
    ]
