# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 12:01
from __future__ import unicode_literals

from django.db import migrations
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_link', '0007_jslinklist_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='jslink',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes'),
        ),
    ]
