# Generated by Django 2.2.13 on 2020-07-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_link', '0010_jslink_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jslink',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
